[package]
name = "wrapper-ffi"
version = "0.1.0"
edition = "2021"

[lib]
name = "wrapper"
crate-type = ["staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
